package com.rules
import org.jeecg.modules.demo.emergencycompile.entity.Emergency;

rule "事故灾难：一般事故"
    activation-group "事故灾难"
    salience 1
    when
        $e:Emergency((0< deathNum  && deathNum  <= 3)  ||
                     (0< injuryNum && injuryNum <= 10) )
    then
        $e.setEmergencyLevel("4");
        update($e)
        System.out.println("事故灾难：一般事故");
    end

rule "事故灾难：较大事故"
    activation-group "事故灾难"
    salience 2
    when
        $e:Emergency((3 < deathNum && deathNum <= 10)  ||
                     (10 < injuryNum && injuryNum <= 50) )
    then
        $e.setEmergencyLevel("3");
        update($e)
        System.out.println("事故灾难：较大事故");
    end

rule "事故灾难：重大事故"
    activation-group "事故灾难"
    salience 3
    when
        $e:Emergency((10 < deathNum && deathNum <= 30)  ||
                     (50 < injuryNum && injuryNum <= 100) )
    then
        $e.setEmergencyLevel("2");
        update($e)
        System.out.println("事故灾难：重大事故");
    end

rule "事故灾难：特别重大事故"
    activation-group "事故灾难"
    salience 4
    when
        $e:Emergency((30 < deathNum) ||
                     (100 < injuryNum) )
    then
        $e.setEmergencyLevel("1");
        update($e)
        System.out.println("事故灾难：特别重大事故");
    end


rule otherRule
    agenda-group "other"

    when

    then
        System.out.println("其他规则被触发");
    end